name: SonarCloud Analysis

# Trigger workflow on pushes to develop or any feature branch, and on pull requests to develop
on:
  push:
    branches:
      - develop
      - feature/*

  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3

      # Setup Node.js environment
      - uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use your Node.js version

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Run SonarCloud Scan
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectKey: shahdev32_shahdev
          organization: shahdev32
          token: ${{ secrets.SONAR_TOKEN }}
